name: Build Projects

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: app-a
          path: apps/app-a/dist
      - uses: actions/upload-artifact@v4
        with:
          name: app-b
          path: apps/app-b/dist
